name: Willboosterify
on:
  schedule:
    - cron: 0 5 * * 0
  workflow_dispatch:
jobs:
  wbfy:
    uses: WillBooster/reusable-workflows/.github/workflows/wbfy.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.PUBLIC_GH_BOT_PAT }}
